(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(auto-compression-mode t nil (jka-compr))
 '(case-fold-search t)
 '(column-number-mode t)
 '(current-language-environment "Cyrillic-ISO")
 '(default-input-method "cyrillic-yawerty")
 '(global-font-lock-mode t nil (font-lock))
 '(inhibit-startup-screen t)
 '(global-linum-mode t))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;;(set-face-attribute 'default nil :height 90)
(set-face-attribute 'default nil :height 110)

(put 'upcase-region 'disabled nil)
